# Dockerfile to build image for ROS2 Jazzy with nvidia gpu for development of I2R sde_ws

FROM nvidia/cuda:12.8.1-base-ubuntu24.04

ARG ros_distro=jazzy
ENV ROS_DISTRO=$ros_distro
ARG cuda_ver=12.8.1
ARG UID
ARG GID
ARG release_date=2026Feb16
ARG release_ver=i2r-sde_1.0.1-1.deb
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Singapore

# allow nvidia container toolkit
ENV NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,compute,utility,display

# Env for cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda-${cuda_ver}/lib64:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-${cuda_ver}/lib64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
ENV PATH=/usr/local/cuda-${cuda_ver}/bin:$PATH
ENV CUDA_ROOT=/usr/local/cuda-${cuda_ver}

# # enable auto completion for apt install
COPY docker/config_dev_${ros_distro}/docker-clean /root/docker-clean
RUN cp /root/docker-clean /etc/apt/apt.conf.d/docker-clean && \
    rm /root/docker-clean

# setup locale (removed sudo from apt-get, locale and update lines)
RUN apt-get update && apt-get upgrade -y && apt-get -y install locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8

# Ensure Ubuntu Universe repository is enabled
RUN apt-get update && apt-get install -y curl gnupg lsb-release software-properties-common apt-transport-https
RUN add-apt-repository universe

# Install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -q -y --no-install-recommends sudo \
    wget \
    cmake \
    openssh-server \
    htop \
    git \
    libopenmpi-dev \
    python3-dev \
    python3-pip \
    zlib1g-dev \
    make \
    gcc \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    libffi-dev \
    freeglut3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    python3-gst-1.0 \
    libglib2.0-dev \
    ubuntu-restricted-extras \
    libgstreamer-plugins-base1.0-dev \
    nmap \
    dbus-x11 \
    xdg-utils \
    virtualenv \
    mesa-utils

RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ros_distro-desktop-full \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    build-essential
    
# Install sublime & terminator
RUN wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
RUN apt-get update && apt-get install -y sublime-text terminator nautilus tmux

# Force Install of missing dependencies
RUN apt-get -y -f install && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the image / directory
COPY docker/config_dev_${ros_distro}/requirements.txt /requirements.txt

# Setup venv with Python3.10 as version compatible with ROS2 Python colcon build
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install -y \
        python3.10 \
        python3.10-venv \
        python3.10-dev && \
    rm -rf /var/lib/apt/lists/*

RUN python3.10 -m venv /opt/venv_py310
ENV PATH="/opt/venv_py310/bin:$PATH"

# RUN --mount=type=cache,target=/root/.cache/pip \
    # pip install -r requirements.txt

# Install the Python dependencies
RUN pip install -r requirements.txt
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cu128
RUN pip install genesis-world==0.3.14
RUN pip uninstall -y opencv-python opencv-python-headless
RUN export CMAKE_ARGS="-D WITH_FFMPEG=ON -D CMAKE_BUILD_TYPE=RELEASE" && pip install --no-binary opencv-python opencv-python-headless --force-reinstall opencv-python opencv-python-headless
RUN pip install onnxruntime-gpu==1.20.0 # requirements.txt listed but not installed so installing manually
RUN pip install rosbags==0.11.0         # requirements.txt listed but not installed so installing manually
RUN pip install packaging==25.0         # requirements.txt listed but not installed so installing manually
RUN pip install lerobot==0.4.3          # requirements.txt listed but not installed so installing manually
RUN pip install torchvision torch==2.8.0 --index-url https://download.pytorch.org/whl/cu128
RUN pip install numpy==1.26.4
RUN pip install setuptools==79.0.1

# Install apt dependencies
RUN curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc | sudo tee /etc/apt/keyrings/robotpkg.asc
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | sudo tee /etc/apt/sources.list.d/robotpkg.list

RUN apt update && apt install -y --no-install-recommends \
    robotpkg-pinocchio \
    robotpkg-py312-pinocchio \
    ros-jazzy-tf-transformations \
    && rm -rf /var/lib/apt/lists/*

# Copy bashrc
COPY --chmod=755 docker/config_dev_${ros_distro}/bashrc /root/.bashrc

COPY docker/config_dev_${ros_distro}/onnxruntime-linux-x64-gpu-1.15.1 /root/onnxruntime-linux-x64-gpu-1.15.1
ENV ONNXRUNTIME_DIR=/root/onnxruntime-linux-x64-gpu-1.15.1

RUN cd /root/ && git clone --recursive https://github.com/open-mmlab/mmdeploy.git
RUN . /root/.bashrc && mkdir /root/mmdeploy/build && cd /root/mmdeploy/build && cmake .. \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES=gpu \
    -DMMDEPLOY_TARGET_BACKENDS=ort \
    -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR} && \
    make -j12 && make install

# linkage for libfastrtps for booster_robotics_sdk
RUN ln -s /usr/lib/x86_64-linux-gnu/libtinyxml2.so.10 \
    /usr/lib/x86_64-linux-gnu/libtinyxml2.so.9

# Install tool to make release
# RUN curl -sSL "https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository" | sudo bash
# RUN apt install -y glab

# add user ID to docker container
RUN /bin/bash -c 'echo -e "export USER='root'" >> /root/.bashrc && source /root/.bashrc'

# setup for terminator
COPY docker/config_dev_${ros_distro}/terminator_config /root/.config/terminator/config

# Make SSH available
EXPOSE 22

# copy entrypoint
COPY --chmod=755 docker/config_dev_${ros_distro}/ros_entrypoint_$ROS_DISTRO.sh /ros_entrypoint.sh 

# tmux setup
RUN /bin/bash -c 'git clone https://github.com/tmux-plugins/tpm /root/.tmux/plugins/tpm'
COPY docker/config_dev_${ros_distro}/tmux.conf /root/.tmux.conf 

# setup entrypoint for docker 
WORKDIR /root
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD [". ~/.bashrc"]



