# Do not load this file into ROS param server.
# We will parse and extract the contents using yaml instead.   

# For pose initialization
start_configuration: [
    -0.0, 0.0, 
    -0.38222880210084487, -1.2963246176472716,
    0.2636047653283989, -0.5669896132337005, 
    -0.4074082089873005, -0.05507912409246853,
    -0.09787296129607195, -0.38261117659935123, 
    1.2965775931338805, 0.2626643999916205,
    0.566245416609455, -0.40659248112759494, 
    0.05508546217473252, 0.09865729221960956,
    -0., -0., 
    0.0, 0.0,
    0.0, 0.0, 
    0.0, 0.0,
    0.0, 0.0, 
    0.0, 0.0,
    0.0
  ]

# For pose stopping
end_configuration: [
  -0.0, 0.9, 
  -0.07839322835206985, -1.371374750137329,
  0.05893797054886818, -0.06771191209554672, 
  -0.0, 0.010109102353453636,
  -0.02002716064453125, -0.07839322835206985, 
  1.371374750137329, 0.13942931592464447,
  0.06198977679014206, -0.01926422119140625, 
  -0.01926422119140625, -0.00667582219466567,
  -0., -0., 
  0.0, 0.0,
  0.0, 0.0, 
  0.0, 0.0,
  0.0, 0.0, 
  0.0, 0.0,
  0.0
]

joint_kps: [
      5., 5.,
      100., 100., 70., 70., 50., 70., 50.,
      100., 100., 70., 70., 50., 70., 50.,
      100., 
      350., 350., 180., 350., 450., 450.,
      350., 350., 180., 350., 450., 450.
  ]

joint_kds: [
      .1, .1,
      1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
      1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
      5.0,
      7.5, 7.5, 3., 5.5, 0.5, 0.5,
      7.5, 7.5, 3., 5.5, 0.5, 0.5
  ]

joint_limits:
  AAHead_yaw:
    min_position: -1.57
    max_position: 1.57
  Head_pitch:
    min_position: -0.35
    max_position: 1.22
  Left_Shoulder_Pitch:
    min_position: -3.31
    max_position: 1.22
  Left_Shoulder_Roll:
    min_position: -1.74
    max_position: 1.57
  Left_Elbow_Pitch:
    min_position: -2.27
    max_position: 2.27
  Left_Elbow_Yaw:
    min_position: -2.27
    max_position: 2.27
  Left_Wrist_Pitch:
    min_position: -2.27
    max_position: 2.27
  Left_Wrist_Yaw:
    min_position: -2.27
    max_position: 2.27
  Left_Hand_Roll:
    min_position: -2.27
    max_position: 2.27
  Right_Shoulder_Pitch:
    min_position: -3.31
    max_position: 1.22
  Right_Shoulder_Roll:
    min_position: -1.57
    max_position: 1.74
  Right_Elbow_Pitch:
    min_position: -2.27
    max_position: 2.27
  Right_Elbow_Yaw:
    min_position: -2.27
    max_position: 2.27
  Right_Wrist_Pitch:
    min_position: -2.27
    max_position: 2.27
  Right_Wrist_Yaw:
    min_position: -2.27
    max_position: 2.27
  Right_Hand_Roll:
    min_position: -2.27
    max_position: 2.27
  Waist_joint:
    min_position: -1.57
    max_position: 1.57
  Left_Hip_Pitch:
    min_position: -1.8
    max_position: 1.57
  Left_Hip_Roll:
    min_position: -0.3
    max_position: 1.57
  Left_Hip_Yaw:
    min_position: -1.0
    max_position: 1.0
  Left_Knee_Pitch:
    min_position: 0.0
    max_position: 2.34
  Left_Ankle_Pitch:
    min_position: -0.87
    max_position: 0.35
  Left_Ankle_Roll:
    min_position: -0.44
    max_position: 0.44
  Right_Hip_Pitch:
    min_position: -1.8
    max_position: 1.57
  Right_Hip_Roll:
    min_position: -1.57
    max_position: 0.3
  Right_Hip_Yaw:
    min_position: -1.0
    max_position: 1.0
  Right_Knee_Pitch:
    min_position: 0.0
    max_position: 2.34
  Right_Ankle_Pitch:
    min_position: -0.87
    max_position: 0.35
  Right_Ankle_Roll:
    min_position: -0.44
    max_position: 0.44
