#!/bin/bash

# --------------------------------------------------
# This script will read the contents of the directory
# generated by catkin_make install and create a
# .deb package
# @author Ng Kam Pheng
# @email ngkp@a-star.edu.sg
# --------------------------------------------------

# retrieve a non-empty string
function getNonEmptyString()
{
    local strval=""
    while [ -z "$strval" ]
    do
        read strval
    done
    echo $strval
}

# checks if input is an external pacakge
# function isExternalPackage()
# {
#     local is_external=0
#     if [ "$1" == "gz-to-ros-perfect-localization" ] || \
#        [ "$1" == "neo2_msgs" ] || \
#        [ "$1" == "p3dx_description" ] || \
#        [ "$1" == "p3dx_gazebo" ] || \
#        [ "$1" == "p3dx_navigation" ] || \
#        [ "$1" == "p3dx_viz" ] || \
#        #[ "$1" == "ridable_robot_msgs" ] || \ need this for i2r_system_monitor!
#        [ "$1" == "rosaria" ] || \
#        [ "$1" == "rosaria_msgs" ] || \
#        [ "$1" == "sam_attached_controller_msgs" ] || \
#        [ "$1" == "scout_msgs" ] || \
#        [ "$1" == "xnergy_charger_driver_interfaces" ] || \
#        [ "$1" == "i2r_ros_template" ]   # technically not external template, but we don't want to package it
#     then 
#         is_external=1
#     fi 
#     echo $is_external
# }

# make sure we have the input install directory name
if [ $# -lt 2 ]
then
    echo -e "\nUsage: $0 <input_install_directory> <target_directory>"
    echo -e "Example: $0 install /opt/ros/jazzy\n"
    exit
fi

echo -e "\nAre the required robots as listed in sde_robot_config/config correct [y/n]? \c"
read check_response
if [ "$check_response" != "y" ]
then
    echo -e "\nPlease check and edit and run this tool again\n\n"
    exit
fi

# for every one of the packages, check for existance of these directories
ros2pkgs_list=`ls -1t $1`
IFS=$'\n' read -rd '' -a ros2pkgs_arr <<<"$ros2pkgs_list"
for currpkg in "${ros2pkgs_arr[@]}"
do
    if [ -f "$1/${currpkg}" ]
    then
        echo "skipping file $1/${currpkg}"
        continue
    fi

    # we will skip packaging these external_packages
    # ext_pkg=$(isExternalPackage $currpkg)
    # if [[ $ext_pkg == 1 ]]
    # then 
    #     echo "skipping package $currpkg"
    #     continue 
    # fi 

    if [ ! -d "$1/${currpkg}/lib" ]
    then
        echo -e "\033[1;33mWarning! $1/${currpkg}/lib doesn't exist!\033[0m\n"
    else
        echo -e "\033[0;32mOK - $1/${currpkg}/lib \033[0m"
    fi

    if [ ! -d "$1/${currpkg}/share" ]
    then
        echo -e "\n\033[0;31mError! $1/${currpkg}/share doesn't exist!\033[0m\n"
        exit
    fi
    echo -e "\033[0;32mOK - $1/${currpkg}/share \033[0m"

    if [ ! -d "$1/${currpkg}/include" ]
    then
        #echo -e "\033[1;33mWarning! $1/${currpkg}/include doesn't exist!\033[0m"
        :
    else
        echo -e "\033[0;32mOK - $1/${currpkg}/include directory \033[0m"
    fi
done 

if [ -z "$2" ]
then
    echo -e "\n\033[0;31mError! target directory cannot be blank!\033[0m\n"
    exit
fi
echo -e "\033[0;32mOK - target directory " $2 "\033[0m"

# check for USING_REGISTER_ROBOT_KEY
# echo -e "\n\033[0;36mPlease verify the register robot key\033[0m"
# register_robot_keys=(`fgrep -R USING_REGISTER_ROBOT_KEY --include={CMakeLists.txt,common_cmakelists.txt}`)
# for rkey in "${register_robot_keys[@]}"
# do
#     echo -e "\033[0;36m$rkey\033[0m"
# done

echo -e "\n\033[0;36mPlease verify the robot launch directories as well\033[0m"

# ask user to give final confirmation
echo -e "\nAre these correct [y/n]? \c"
read check_response
if [ "$check_response" != "y" ]
then
    echo -e "\nPlease check and edit and run this tool again\n\n"
    exit
fi

input_dir=$1
target_dir=$2
package_name=""
version=""
contents=""
inputdone=0
while [ "$inputdone" -eq 0 ]
do
# special check for package name
    package_name=""
    while [ -z "$package_name" ]
    do
        echo -e "Package name: \c"
        package_name=$(getNonEmptyString)
        if [[ $package_name =~ [^0-9a-zA-Z\-] ]]
        then
            package_name=""
        fi
    done

# version cannot be blank
    echo -e "Version <MAJOR>.<MINOR>.<BUGFIX>-<PACKAGEVERSION>: \c"
    version=$(getNonEmptyString)

# base can use default
    echo -e "Section: [base] \c"
    read section
    if [ -z "$section" ]
    then
        section="base"
    fi

# priority can use default
    echo -e "Priority: [optional] \c"
    read priority
    if [ -z "$priority" ]
    then
        priority="optional"
    fi

# architecture can use default
    architecture=`dpkg --print-architecture`
    echo -e "Architecture: [$architecture] \c"
    read architecture
    if [ -z "$architecture" ]
    then
        architecture=`dpkg --print-architecture`
    fi

# maintainer name can use default
    echo -e "Maintainer name: [name] \c"
    read maintainer_name
    if [ -z "$maintainer_name" ]
    then
        maintainer_name="name"
    fi

# maintainer email can use default
    echo -e "Maintainer email: [email@unknown.address] \c"
    read maintainer_email
    if [ -z "$maintainer_email" ]
    then
        maintainer_name="email@unknown.address"
    fi

# description can be use default
    echo -e "Description: [default description] \c"
    read description
    if [ -z "$description" ]
    then
        description="default description"
    fi

# form the directory name
dir_name="${package_name}_${version}"

# update sde_version_number.txt in sde_robot_config
fname_sde_version_number=${PWD}/`find install -name sde_version_number.txt`
if [ ! -e "$fname_sde_version_number" ]
then 
    echo -e "\n===> Error! Failed to find the file fname_sde_version_number"
    exit
else    
    `echo ${dir_name} > $fname_sde_version_number`
fi 
vnum=`cat $fname_sde_version_number`
echo -e "\nupdated package/version to ${fname_sde_version_number} to ${vnum}"

# ask user to verify
    contents="Package: $package_name\nVersion: $version\nSection: $section\nPriority: $priority\nArchitecture: $architecture\nMaintainer: $maintainer_name <$maintainer_email>\nDescription: $description"
    echo -e "\n$contents\n\nIs this correct <y/n>? \c"

    read response
    if [ "$response" = "y" -o "$response" = "Y" ]
    then
        inputdone=1
    fi
done

# create the debian file
`mkdir -p $dir_name/DEBIAN`
`echo -e $contents > $dir_name/DEBIAN/control`
if [ -z "$dir_name/DEBIAN/control" ]
then
    echo -e "\n===> Error! Failed to create $dir_name/DEBIAN/control\n"
    exit
fi

# create the target directory
newdir=""
if [[ "$target_dir" =~ ^\/.* ]]
then
    newdir="${dir_name}${target_dir}"
else
    newdir="${dir_name}/${target_dir}"
fi
`mkdir -p $newdir/lib`
`mkdir -p $newdir/share`
`mkdir -p $newdir/include`
`mkdir -p $newdir/meshes`
`mkdir -p $newdir/local`

for currpkg in "${ros2pkgs_arr[@]}"
do
    if [ -f "$1/${currpkg}" ]
    then
        echo "skipping file $1/$currpkg $newdir"
        continue 
    fi 

    # we will skip packaging these external_packages
    # ext_pkg=$(isExternalPackage $currpkg)
    # if [[ $ext_pkg == 1 ]]
    # then 
    #     echo "skipping package $currpkg"
    #     continue 
    # fi 

    if [ -d "$1/$currpkg/lib" ]
    then
        `cp -r $1/$currpkg/lib $newdir`
    fi

    if [ -d "$1/$currpkg/share" ]
    then
        `cp -r $1/$currpkg/share $newdir`
    fi

    if [ -d "$1/$currpkg/include" ]
    then
        `cp -r $1/$currpkg/include $newdir`
    fi

    if [ -d "$1/$currpkg/meshes" ]
    then
        `cp -r $1/$currpkg/meshes $newdir`
    fi
    if [ -d "$1/$currpkg/local" ]
    then
        `cp -r $1/$currpkg/local $newdir`
    fi
done 

# need to package the local folder? 

# package it now
dpkg-deb --build $dir_name
if [ -z "${dir_name}.deb" ]
then
    echo -e "\n===> Error! Faled to create ${dir_name}.deb"
else
    echo -e "\nDone!"
fi
